loggers:
  octoprint.events:
    level: DEBUG
  octoprint.filemanager:
    level: DEBUG
  octoprint.filemanager.storage:
    level: INFO
  octoprint.plugin:
    level: INFO
  octoprint.plugins.file_check:
    level: DEBUG
  octoprint.plugins.helloworld:
    level: DEBUG
  octoprint.plugins.queue:
    level: DEBUG
  octoprint.plugins.virtual_printer:
    level: INFO
