_version: 2
oprint:
  active: true
  apikey: null
  groups:
  - admins
  - users
  password: $argon2id$v=19$m=65536,t=3,p=4$EUKotXbuPUfI+T8HIGRMiQ$uz3Dy1IX8bh5F69USKfAWxUz1fQO5I9mMpoHjeChMxY
  permissions: []
  roles:
  - user
  - admin
  settings: {}
