_version: 2
oprint:
  active: true
  apikey: null
  groups:
  - admins
  - users
  password: $argon2id$v=19$m=65536,t=3,p=4$SgnhfK+VsrYWImRM6T2ntA$mKBOFd6VVNoJNLn/J8Lcc8iqWuD4ETgaZTFxZBTTynA
  permissions: []
  roles:
  - user
  - admin
  settings: {}
